name: Build and push aeriOS Self-awareness hardware info component container image to Docker Hub

on:
  push:
    branches: [ "main" ]
    paths:
      - "hardware_info/**"
  pull_request:
    branches: [ "main" ]
    paths:
      - "hardware_info/**"
  workflow_dispatch: {}  # allows manual trigger

env:
  IMAGE_NAME: eclipseaerios/self-awareness-hardware-info
  VERSION: 1.4.4

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to Docker Hub
      if: ${{ github.event_name != 'pull_request' }}
      uses: docker/login-action@v3
      with:
        registry: docker.io
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Set short SHA
      id: shortsha
      run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT"

    - name: Build and push the container image
      uses: docker/build-push-action@v6
      with:
        context: ./hardware_info
        file: ./hardware_info/Dockerfile
        push: ${{ github.event_name != 'pull_request' }}
        platforms: linux/amd64,linux/arm64
        tags: |
          ${{ env.IMAGE_NAME }}:latest
          ${{ env.IMAGE_NAME }}:${{ env.VERSION }}
          ${{ env.IMAGE_NAME }}:${{ steps.shortsha.outputs.SHORT_SHA }}

    - name: Build and push the container image for RISC-V (experimental)
      uses: docker/build-push-action@v6
      with:
        context: ./hardware_info
        file: ./hardware_info/Dockerfile_risc-v
        push: ${{ github.event_name != 'pull_request' }}
        platforms: linux/riscv64
        tags: |
          ${{ env.IMAGE_NAME }}:latest-riscv
          ${{ env.IMAGE_NAME }}:${{ env.VERSION }}-riscv
          ${{ env.IMAGE_NAME }}:${{ steps.shortsha.outputs.SHORT_SHA }}-riscv
